{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.fullname" . }}-postgresql
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "temporal.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "temporal.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
