{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.fullname" . }}-postgresql
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "temporal.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.database.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database.name | quote }}
{{- end }}
