{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
{{- end }}
