apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "temporal.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "temporal.server.labels" . | nindent 4 }}
data:
  development.yaml: |
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
        constraints: {}
    frontend.enableUpdateWorkflowExecution:
      - value: true
        constraints: {}
    limit.maxIDLength:
      - value: 255
        constraints: {}
